server:
  port: 8080
  servlet.context-path: /api

spring:
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration/
    schemas: public
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        default_schema: public
    hibernate:
      ddl-auto: none
      default_schema: public
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://62.113.105.28:6666/grocery
    username: user
    password: pswd

fixedDelay.in.milliseconds: 86400000

logging.level.root: INFO



